"""A tool script for managing build information."""

import datetime
import os
import subprocess
import sys
import json

project_dir = os.path.realpath(os.path.join(os.path.dirname(__file__), ".."))

if __name__ != "__main__":
    raise ImportError("This script is not meant to be imported.")

cmd = sys.argv[1] if len(sys.argv) > 1 else ""

if cmd == "gen":
    try:
        # Get current commit hash
        commit_hash = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], 
            stderr=subprocess.DEVNULL
        ).decode("utf-8").strip()

        # Get current branch
        branch = subprocess.check_output(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            stderr=subprocess.DEVNULL
        ).decode("utf-8").strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        commit_hash = "unknown"
        branch = "unknown"

    version = None
    try:
        # This gets tags that point to the current commit
        tag = subprocess.check_output(
            ["git", "describe", "--exact-match", "--tags", "HEAD"],
            stderr=subprocess.DEVNULL
        ).decode("utf-8").strip()

        if tag.startswith("v"):
            version = tag[1:]
        else:
            print("No version found.")
    except subprocess.CalledProcessError:
        print("No tag found for the current commit.")

    time = datetime.datetime.now().timestamp()

    with open(os.path.join(project_dir, "build", "_build_info.py"), "w", encoding="utf-8") as file:
        file.write(
        """# This file is auto-generated by build_info_tool.py
# Do not edit this file manually.
# It contains build information for the application.

BUILD_INFO = """)
        file.write(json.dumps({
            "version": version,
            "build_time": time,
            "commit_hash": commit_hash,
            "branch": branch
        }, indent=2).replace("null", "None"))
elif cmd == "del":
    os.remove(os.path.join(project_dir, "build", "_build_info.py"))
else:
    print("Invalid command. Use 'gen' to generate build info or 'del' to delete it.")
